name: GitHub Classroom Workflow

on: [push]

jobs:
  build-linux:
    permissions: write-all
    name: Autograding
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Set PYTHONPATH to see project modules
      run: |
         echo "PYTHONPATH=$GITHUB_WORKSPACE/src" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base

    - name: Show Python versions
      id: show-python-versions
      uses: etamu-class/autograding-command-grader@v10
      with:
        test-name: 'Show Python versions'
        setup-command: ''
        command: 'python src/python_versions.py'
        timeout: '10'
        max-score: '0'

    - name: Test Assignment Notebook runs all cells cleanly
      id: test-assignment-notebook
      uses: etamu-class/autograding-command-grader@v10
      with:
        test-name: 'Test Assignment Notebook'
        working-directory: './notebooks'
        setup-command: ''
        command: 'jupyter nbconvert --execute Assg-04-Regression-Learning-Curves-Regularization.ipynb --to notebook'
        timeout: '10'
        max-score: '20'

    - name: Task 1 test task1_load_data()
      id: test-task-1
      uses: etamu-class/autograding-command-grader@v10
      with:
        test-name: 'Test Task 1'
        setup-command: ''
        command: 'python -m twisted.trial test_assg_tasks.test_task1_load_data'
        timeout: '10'
        max-score: '10'

    - name: Task 2 test task2_underfit_model()
      id: test-task-2
      uses: etamu-class/autograding-command-grader@v10
      with:
        test-name: 'Test Task 2'
        setup-command: ''
        command: 'python -m twisted.trial test_assg_tasks.test_task2_underfit_model'
        timeout: '10'
        max-score: '10'

    - name: Task test learning_curve_errors()
      id: test-task-3
      uses: etamu-class/autograding-command-grader@v10
      with:
        test-name: 'Test Task 3'
        setup-command: ''
        command: 'python -m twisted.trial test_assg_tasks.test_learning_curve_errors'
        timeout: '10'
        max-score: '10'

    - name: Task 4 test task4_overfit_model()
      id: test-task-4
      uses: etamu-class/autograding-command-grader@v10
      with:
        test-name: 'Test Task 4'
        setup-command: ''
        command: 'python -m twisted.trial test_assg_tasks.test_task4_overfit_model'
        timeout: '10'
        max-score: '10'

    - name: Task 5 test task5_lasso_model()
      id: test-task-5
      uses: etamu-class/autograding-command-grader@v10
      with:
        test-name: 'Test Task 5'
        setup-command: ''
        command: 'python -m twisted.trial test_assg_tasks.test_task5_lasso_model'
        timeout: '10'
        max-score: '10'

    - name: Task 6 test task6_ridge_model()
      id: test-task-6
      uses: etamu-class/autograding-command-grader@v10
      with:
        test-name: 'Test Task 6'
        setup-command: ''
        command: 'python -m twisted.trial test_assg_tasks.test_task6_ridge_model'
        timeout: '10'
        max-score: '10'

    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-ASSIGNMENT-NOTEBOOK_RESULTS: "${{steps.test-assignment-notebook.outputs.result}}"
        TEST-TASK-1_RESULTS: "${{steps.test-task-1.outputs.result}}"
        TEST-TASK-2_RESULTS: "${{steps.test-task-2.outputs.result}}"
        TEST-TASK-3_RESULTS: "${{steps.test-task-3.outputs.result}}"
        TEST-TASK-4_RESULTS: "${{steps.test-task-4.outputs.result}}"
        TEST-TASK-5_RESULTS: "${{steps.test-task-5.outputs.result}}"
        TEST-TASK-6_RESULTS: "${{steps.test-task-6.outputs.result}}"
      with:
        runners: test-assignment-notebook,test-task-1,test-task-2,test-task-3,test-task-4,test-task-5,test-task-6
